# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
