# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_tag_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='article_num',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
