# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='child_reply_input',
            field=models.BooleanField(default=False),
        ),
    ]
