# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comment_reply_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply_to',
            new_name='reply_to_some',
        ),
    ]
