# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170316_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply_to_some',
            new_name='reply_to',
        ),
    ]
