# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170316_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply_to',
            new_name='reply',
        ),
    ]
