# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170316_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
