# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comment_send_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
