# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170320_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='create_year',
        ),
    ]
