# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_article_create_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
