# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_article_url_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
