# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_comment_user_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_view_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='view_num',
            field=models.IntegerField(default=0),
        ),
    ]
