# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20170601_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_ip', models.CharField(default=0, max_length=100)),
                ('view_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='ViewNum',
        ),
    ]
