# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20170601_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
